force-app/main/objects/Error_Log__e/Error_Log__e.object-meta.xml
<CustomObject>
    <description>This log receives the Error information and pass it to integration object</description>
    <label>Error Log</label>
    <pluralLabel>Error Logs</pluralLabel>
</CustomObject>

force-app/main/objects/Error_Log__e/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>Error type accepted values are Apex,Workflow,Process Builder,Flows,LC</description>
    <label>Error Source</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/ErrorLog__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This field will store the impacted component(Apex class,lightning component,Workflow,Process builder,Flow)&apos;s name</description>
    <label>Component Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the error message of the actual exception</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <inlineHelpText>This field will store the source of error from where the error has invoked.</inlineHelpText>
    <label>Error Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/Log_Trace_Utils__mdt/Log_Trace_Utils__mdt.object-meta.xml
<CustomObject>
    <label>Log Trace Util</label>
    <pluralLabel>Log Trace Util</pluralLabel>
</CustomObject>

force-app/main/default/classes/GenericErrorLoggerClassTest.cls
@isTest
private class GenericErrorLoggerClassTest {
    @isTest
    private static void testDMLLogException() {
      Test.startTest(); 
      try
       {
          insert new Account(Rating='Hot');
       }catch(Exception ee)
       {
        GenericErrorLoggerClass.logException(ee,'GenericErrorLoggerClassTest');
        Test.getEventBus().deliver(); 
       }
       Test.stopTest();
       System.assertEquals(1, [SELECT Id FROM ErrorLog__c].size());
    }
    @isTest
    private static void testQueryLogException() {
      Test.startTest(); 
      try
       {
          Account acc = [SELECT Id FROM Account WHERE Id='001234234435w23'];
       }catch(Exception ee)
       {
        GenericErrorLoggerClass.logException(ee,'GenericErrorLoggerClassTest');
        Test.getEventBus().deliver(); 
       }
       Test.stopTest();
       System.assertEquals(1, [SELECT Id FROM ErrorLog__c].size());
    }
    @isTest
    private static void testInterfaceExtendedClass() {
        Test.startTest(); 
        Log_Trace_Utils__mdt errorLogEventInstance = Log_Trace_Utils__mdt.getInstance(ErrorLogEventTriggerHandler.TRIGGER_METADATA);
        list<Error_Log__e> errorLogList = new list<Error_Log__e>();
        errorLogList.add(new Error_Log__e(Error_Message__c='Test Error',
                                          Error_Source__c = 'Apex',
                                          Component_Name__c = 'GenericErrorLoggerClassTest'
                                         )
                        );
        ErrorLogEventTriggerHandler.callExtensionClass(errorLogEventInstance, errorLogList);
        Test.stopTest();
        System.assertEquals(1, [SELECT Id FROM ErrorLog__c].size());
    }
}