force-app/main/objects/Error_Log__e/Error_Log__e.object-meta.xml
<CustomObject>
    <description>This log receives the Error information and pass it to integration object</description>
    <label>Error Log</label>
    <pluralLabel>Error Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log__e/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <description>Id of current user</description>
    <label>Current User</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/Error_Log__e/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>Error type accepted values are Apex,Workflow,Process Builder,Flows,LC</description>
    <label>Error Source</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Error_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Error_Stacktrace__c</fullName>
    <label>Error Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Limits_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Limits_Snapshot__c</fullName>
    <description>This field capture the  limit snapshot which represents the Apex profiling</description>
    <inlineHelpText>This field capture the  limit snapshot which represents the Apex profiling</inlineHelpText>
    <label>Limits Snapshot</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/Error_Log__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>This field will store the line number from the impacted salesforce component.</description>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GenericErrorLoggerClass.cls
/**
 * @Author: Ranjan Singh
 * Created Date: 21.07.2023
 * @description: The GenericErrorLoggerClass provides a utility method to log exceptions in Salesforce
 *               as platform events for error tracking and analysis.
 */
public class GenericErrorLoggerClass {
	/**
	 * Created By: Ranjan Singh
     * @description: Logs the given exception as a platform event for error tracking.
     * @param exceptionInstance The exception to be logged.
     * @param componentName The name of the component where the exception occurred.
     */
    public static void logException(System.Exception exceptionInstance, String componentName)
    {
        Error_Log__e errorLogInstance = new Error_Log__e(
        												 Component_Name__c = componentName,
            											 Current_User__c = UserInfo.getUserId(),
            											 Error_Message__c = exceptionInstance.getMessage(),
            											 Error_Stacktrace__c = exceptionInstance.getStackTraceString(),
            											 Error_Source__c = String.valueOf(Request.getCurrent().getQuiddity()),
        												 Exception_Type__c = exceptionInstance.getTypeName(),
            											 Limits_Snapshot__c = GenericErrorLoggerUtilityClass.getLimitDetails(),
            											 Line_Number__c =  exceptionInstance.getLineNumber()
        												);
        
        errorLogInstance = GenericErrorLoggerUtilityClass.getExceptionTypeAddionalDetails(exceptionInstance, errorLogInstance);
        system.debug('errorLogInstance**'+errorLogInstance);
        EventBus.publish(errorLogInstance);
    }
}