force-app/main/objects/Error_Log__e/Error_Log__e.object-meta.xml
<CustomObject>
    <description>This log receives the Error information and pass it to integration object</description>
    <label>Error Log</label>
    <pluralLabel>Error Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log__e/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <description>Id of current user</description>
    <label>Current User</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/Error_Log__e/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>Error type accepted values are Apex,Workflow,Process Builder,Flows,LC</description>
    <label>Error Source</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Error_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Error_Stacktrace__c</fullName>
    <label>Error Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Inaccessible_Fields_Details__c.field-meta.xml
<CustomField>
    <fullName>Inaccessible_Fields_Details__c</fullName>
    <description>Capture details for Query Exception</description>
    <inlineHelpText>Capture details for Query Exception</inlineHelpText>
    <label>Inaccessible Fields Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <label>Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Limits_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Limits_Snapshot__c</fullName>
    <description>This field capture the  limit snapshot which represents the Apex profiling</description>
    <inlineHelpText>This field capture the  limit snapshot which represents the Apex profiling</inlineHelpText>
    <label>Limits Snapshot</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/Error_Log__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>This field will store the line number from the impacted salesforce component.</description>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/ErrorLog__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This field will store the impacted component(Apex class,lightning component,Workflow,Process builder,Flow)&apos;s name</description>
    <label>Component Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the error message of the actual exception</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <inlineHelpText>This field will store the source of error from where the error has invoked.</inlineHelpText>
    <label>Error Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <inlineHelpText>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Inaccessible_Fields_Details__c.field-meta.xml
<CustomField>
    <fullName>Inaccessible_Fields_Details__c</fullName>
    <label>Inaccessible Fields Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <description>This field will store the governor limit details</description>
    <inlineHelpText>This field will store the governor limit details</inlineHelpText>
    <label>Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>This field will store the line number from the impactesalesforce component.</description>
    <inlineHelpText>This field will store the line number from the impactesalesforce component.</inlineHelpText>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <inlineHelpText>This field will store the salesforce Id of the impacted record.</inlineHelpText>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>This field will store the stack trace of exception. If exception is originated from APEX DML</description>
    <inlineHelpText>This field will store the stack trace of exception. If exception is originated from APEX DML</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/Log_Trace_Utils__mdt/Log_Trace_Utils__mdt.object-meta.xml
<CustomObject>
    <label>Log Trace Util</label>
    <pluralLabel>Log Trace Util</pluralLabel>
</CustomObject>

force-app/main/objects/Log_Trace_Utils__mdt/fields/Is_Extension_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Extension_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is true, then the Override class will be used to process the Platform Event data and store it into a Salesforce object</description>
    <inlineHelpText>If this checkbox is true, then the Override class will be used to process the Platform Event data and store it into a Salesforce object</inlineHelpText>
    <label>Is Extension Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Trace_Utils__mdt/fields/Logging_Extension_Class__c.field-meta.xml
<CustomField>
    <fullName>Logging_Extension_Class__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for Platform Event</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for  Platform Event</inlineHelpText>
    <label>Logging Extension Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/classes/ErrorLogEventTriggerHandler.cls
/**********************************************************************************************
* @Author:      Ranjan Singh
* @Date:        20th July 2023
* @Description: Trigger handler class for ErrorLogEventTrigger.
*               The ErrorLogEventTriggerHandler class handles the platform event trigger for Error_Log__e events.
*               It provides a mechanism to process and log the error events based on custom metadata settings.
*               logging the error information into the organization's error log object or invoking an external logging extension using LoggerInterface
* @TestClass:   GenericErrorLoggerClassTest 
***********************************************************************************************/
public class ErrorLogEventTriggerHandler {
    /**
     * @Title: TRIGGER_METADATA
     * @Description:Constant variable to hold the name of the Custom Metadata Type record used for configuration.
    **/
    public static final string TRIGGER_METADATA = 'Custom_Log_Error_Utils';
    /**
     * @Title: afterInsert
     * @Description:Method invoked after the insertion of Error_Log__e platform event records.
	 *              It processes the events and logs them based on custom metadata settings.
	 * @param errorEventList The list of Error_Log__e platform event records to be processed.
    **/
    public static void afterInsert(list<Error_Log__e> errorEventList)
    {
        try
        {
            Log_Trace_Utils__mdt errorLogEventInstance = Log_Trace_Utils__mdt.getInstance(TRIGGER_METADATA);
            if(errorLogEventInstance?.Is_Extension_Required__c && String.isNotBlank(errorLogEventInstance?.Logging_Extension_Class__c))
            {
                //Dynamically fetch the extension handler class and invoke the method. You can create a new class extending LoggerInterface and write your logging logic there.
                callExtensionClass(errorLogEventInstance, errorEventList);                       
            }else
            {
                list<ErrorLog__c> errorLogList = new list<ErrorLog__c>();  // you can change this to your organization's error logging object here or at the custom metadat level
                for(Error_Log__e errorLogInstance : errorEventList)
                {
                    errorLogList.add(new ErrorLog__c(
                        Error_Message__c = errorLogInstance.Error_Message__c,
                        Error_Source__c = errorLogInstance.Error_Source__c,
                        Exception_Type__c = errorLogInstance.Exception_Type__c,
                        Stack_Trace__c = errorLogInstance.Error_Stacktrace__c,
                        Line_Number__c = errorLogInstance.Line_Number__c,
                        Limits__c = errorLogInstance.Limits_Snapshot__c,
                        Inaccessible_Fields_Details__c = errorLogInstance.Inaccessible_Fields_Details__c,
                        Record_Id__c = errorLogInstance.Record_Id__c,
                        Current_User__c = errorLogInstance.Current_User__c,
                        Component_Name__c = errorLogInstance.Component_Name__c
                    ));
                }
                list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);
            }
            
        }catch(Exception ee)
        {
            if (EventBus.TriggerContext.currentContext().retries < 4) 
            {
                // Condition isn't met, so try again later.
                throw new EventBus.RetryableException( 'Condition is not met, so retrying the trigger again' );
            }else
            {
                // Trigger was retried enough times so give up and
                // resort to alternative action.
                //probably add a seperate record into error log of platform event type  
            }
        }  
    }
    @TestVisible
    private static void callExtensionClass(Log_Trace_Utils__mdt errorLogEventInstance, list<Error_Log__e> errorEventList)
    {
        //Dynamically fetch the extension handler class and invoke the method. You can create a new class extending LoggerInterface and write your logging logic there.
        Type classType = Type.forName(errorLogEventInstance.Logging_Extension_Class__c);  
        LoggerInterface errorLogInterface = (LoggerInterface)classType.newInstance();
        errorLogInterface.execute(errorEventList);    
    }
}