force-app/main/objects/Error_Log__e/Error_Log__e.object-meta.xml
<CustomObject>
    <description>This log receives the Error information and pass it to integration object</description>
    <label>Error Log</label>
    <pluralLabel>Error Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log__e/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <description>Id of current user</description>
    <label>Current User</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/Error_Log__e/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>Error type accepted values are Apex,Workflow,Process Builder,Flows,LC</description>
    <label>Error Source</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Error_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Error_Stacktrace__c</fullName>
    <label>Error Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Inaccessible_Fields_Details__c.field-meta.xml
<CustomField>
    <fullName>Inaccessible_Fields_Details__c</fullName>
    <description>Capture details for Query Exception</description>
    <inlineHelpText>Capture details for Query Exception</inlineHelpText>
    <label>Inaccessible Fields Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <label>Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Limits_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Limits_Snapshot__c</fullName>
    <description>This field capture the  limit snapshot which represents the Apex profiling</description>
    <inlineHelpText>This field capture the  limit snapshot which represents the Apex profiling</inlineHelpText>
    <label>Limits Snapshot</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/Error_Log__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>This field will store the line number from the impacted salesforce component.</description>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/ErrorLog__c/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the error message of the actual exception</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <inlineHelpText>This field will store the source of error from where the error has invoked.</inlineHelpText>
    <label>Error Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <inlineHelpText>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Inaccessible_Fields_Details__c.field-meta.xml
<CustomField>
    <fullName>Inaccessible_Fields_Details__c</fullName>
    <label>Inaccessible Fields Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <description>This field will store the governor limit details</description>
    <inlineHelpText>This field will store the governor limit details</inlineHelpText>
    <label>Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>This field will store the line number from the impactesalesforce component.</description>
    <inlineHelpText>This field will store the line number from the impactesalesforce component.</inlineHelpText>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <inlineHelpText>This field will store the salesforce Id of the impacted record.</inlineHelpText>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>This field will store the stack trace of exception. If exception is originated from APEX DML</description>
    <inlineHelpText>This field will store the stack trace of exception. If exception is originated from APEX DML</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/InterfaceErrorLogExtension.cls
/**********************************************************************************************
* @Author:      Ranjan Singh
* @Date:        24th July 2023
* @Description: The InterfaceErrorLogExtension class implements the LoggerInterface and 
*				provides a method to convert platform event records of type Error_Log__e into custom object records of type ErrorLog__c and insert them into the database.
* @Implements:  LoggerInterface
* @TestClass:   GenericErrorLoggerClassTest 
***********************************************************************************************/
public with sharing class InterfaceErrorLogExtension implements LoggerInterface {
    /**
     * @Title: execute
     * @Description:Converts a list of platform event records of type Error_Log__e into custom object records of type ErrorLog__c and inserts them into the database.
	 * @param logEventList The list of platform event records to be processed and inserted into the database.
    **/
    public static void execute(list<Error_Log__e> logEventList)
    {
        list<ErrorLog__c> errorLogList = new list<ErrorLog__c>();
 		for(Error_Log__e errorLogInstance : logEventList)
        {
            errorLogList.add(new ErrorLog__c(
                Error_Message__c = errorLogInstance.Error_Message__c,
                Error_Source__c = errorLogInstance.Error_Source__c,
                Exception_Type__c = errorLogInstance.Exception_Type__c,
                Stack_Trace__c = errorLogInstance.Error_Stacktrace__c,
                Line_Number__c = errorLogInstance.Line_Number__c,
                Limits__c = errorLogInstance.Limits_Snapshot__c,
                Inaccessible_Fields_Details__c = errorLogInstance.Inaccessible_Fields_Details__c,
                Record_Id__c = errorLogInstance.Record_Id__c,
                Current_User__c = errorLogInstance.Current_User__c
            ));
        }
        list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);
    }
}