force-app/main/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/ErrorLog__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This field will store the impacted component(Apex class,lightning component,Workflow,Process builder,Flow)&apos;s name</description>
    <label>Component Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the error message of the actual exception</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <inlineHelpText>This field will store the source of error from where the error has invoked.</inlineHelpText>
    <label>Error Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <inlineHelpText>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>START</fullName>
            </value>
            <value>
                <fullName>EXECUTE</fullName>
            </value>
            <value>
                <fullName>FINISH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <inlineHelpText>This field will store the salesforce Id of the impacted record.</inlineHelpText>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>This field will store the stack trace of exception. If exception is originated from APEX DML</description>
    <inlineHelpText>This field will store the stack trace of exception. If exception is originated from APEX DML</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/Log_Trace_Utils__mdt/Log_Trace_Utils__mdt.object-meta.xml
<CustomObject>
    <label>Log Trace Util</label>
    <pluralLabel>Log Trace Util</pluralLabel>
</CustomObject>

force-app/main/objects/Log_Trace_Utils__mdt/fields/Is_Extension_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Extension_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is true, then the Override class will be used to process the Platform Event data and store it into a Salesforce object</description>
    <inlineHelpText>If this checkbox is true, then the Override class will be used to process the Platform Event data and store it into a Salesforce object</inlineHelpText>
    <label>Is Extension Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Trace_Utils__mdt/fields/Logging_Extension_Class__c.field-meta.xml
<CustomField>
    <fullName>Logging_Extension_Class__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for Platform Event</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for  Platform Event</inlineHelpText>
    <label>Logging Extension Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/classes/BatchApexErrorEventTriggerHandler.cls
/**********************************************************************************************
* @Author:      Ranjan Singh
* @Date:        22th July 2023
* @Description: The BatchApexErrorEventTriggerHandler class is responsible for handling BatchApexErrorEvent platform events Trigger.
*               logging the error information into the organization's error log object or invoking an external logging extension
*               based on the metadata settings. It processes the BatchApexErrorEvent records in the after-insert trigger context.
* @Implements: LoggerInterface
* @TestClass:   BatchApexErrorEventTest , SamplePlatformEventBatch(for data setup) 
***********************************************************************************************/
public with sharing class BatchApexErrorEventTriggerHandler {
    /** 
     * @Title: TRIGGER_METADATA
     * @Description:Constant variable to hold the name of the Custom Metadata Type record used for configuration.
    **/
	public static final string TRIGGER_METADATA = 'Batch_Apex_Error_Utils';
    /**
     * @Title: afterInsert
     * @Description:Processes the BatchApexErrorEvent records in the after-insert trigger context.
	 *              Depending on the custom metadata settings, it either invokes an external logging extension or inserts error information into the organization's error log object.
	 * @param batchErrorEventList The list of BatchApexErrorEvent records to be processed
    **/
    public static void afterInsert(list<BatchApexErrorEvent> batchErrorEventList)
    {
        try
        {
            Log_Trace_Utils__mdt errorLogEventInstance = Log_Trace_Utils__mdt.getInstance(TRIGGER_METADATA);
            if(errorLogEventInstance?.Is_Extension_Required__c && String.isNotBlank(errorLogEventInstance?.Logging_Extension_Class__c))
            {
                //Dynamically fetch the extension handler class and invoke the method. You can create a new class extending LoggerInterface and write your logging logic there.
                callExtensionClass(errorLogEventInstance, batchErrorEventList);  
            }
            else
            {
                set<Id> asyncApexJobIds = new set<Id>();
                list<ErrorLog__c> errorLogList = new list<ErrorLog__c>(); // you can change this to your organization's error logging object here or at the custom metadat level
                for(BatchApexErrorEvent batchInst : batchErrorEventList)
                {
                    asyncApexJobIds.add(batchInst.AsyncApexJobId);
                }
                Map<Id,AsyncApexJob> asyncIdJobMap = new Map<Id,AsyncApexJob>([SELECT Id, ApexClass.Name 
                                                                               FROM AsyncApexJob 
                                                                               WHERE Id IN :asyncApexJobIds]
                                                                             );        
                
                for(BatchApexErrorEvent errorLogInstance : batchErrorEventList)
                {
                    errorLogList.add(new ErrorLog__c(
                        Component_Name__c = asyncIdJobMap.get(errorLogInstance.AsyncApexJobId)?.ApexClass.Name ,
                        Error_Message__c = errorLogInstance.Message,
                        Error_Source__c = 'Batch Apex',
                        Exception_Type__c = errorLogInstance.ExceptionType,
                        Stack_Trace__c = errorLogInstance.StackTrace,
                        Phase__c = errorLogInstance.Phase,
                        Record_Id__c = errorLogInstance.JobScope
                    ));
                }
                list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);
            }
        }catch(Exception ee)
        {
            if (EventBus.TriggerContext.currentContext().retries < 4) 
            {
                // Condition isn't met, so try again later.
                throw new EventBus.RetryableException( 'Condition is not met, so retrying the trigger again' );
            }else
            {
                // Trigger was retried enough times so give up and
                // resort to alternative action.
                //probably add a seperate record into error log of platform event type  
            }
        }  
    }
    @TestVisible
    private static void callExtensionClass(Log_Trace_Utils__mdt errorLogEventInstance, list<BatchApexErrorEvent> batchErrorEventList)
    {
         //Dynamically fetch the extension handler class and invoke the method. You can create a new class extending LoggerInterface and write your logging logic there.
                Type classType = Type.forName(errorLogEventInstance.Logging_Extension_Class__c);  
                LoggerInterface errorLogInterface = (LoggerInterface)classType.newInstance();
                errorLogInterface.execute(batchErrorEventList);    
    }
}