force-app/main/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/ErrorLog__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This field will store the impacted component(Apex class,lightning component,Workflow,Process builder,Flow)&apos;s name</description>
    <label>Component Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the error message of the actual exception</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <inlineHelpText>This field will store the source of error from where the error has invoked.</inlineHelpText>
    <label>Error Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <inlineHelpText>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Flow_Context_Object__c.field-meta.xml
<CustomField>
    <fullName>Flow_Context_Object__c</fullName>
    <description>This field will map with Context Object field of FlowExecutionErrorEvent. This is reserved for future use</description>
    <inlineHelpText>This field will map with Context Object field of FlowExecutionErrorEvent. This is reserved for future use</inlineHelpText>
    <label>Flow Context Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Flow_Context_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Flow_Context_Record_Id__c</fullName>
    <description>This field will map with Context Record Id field of FlowExecutionErrorEvent. This is reserved for future use</description>
    <inlineHelpText>This field will map with Context Record Id field of FlowExecutionErrorEvent. This is reserved for future use</inlineHelpText>
    <label>Flow Context Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Flow_Element_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Element_API_Name__c</fullName>
    <description>This field will map with ElementApiName field of FlowExecutionErrorEvent.</description>
    <inlineHelpText>This field will map with ElementApiName field of FlowExecutionErrorEvent</inlineHelpText>
    <label>Flow Element API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Flow_Element_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Element_Type__c</fullName>
    <description>This field will map with Element Type field of FlowExecutionErrorEvent.</description>
    <inlineHelpText>This field will map with Element Type field of FlowExecutionErrorEvent.</inlineHelpText>
    <label>Flow Element Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <inlineHelpText>This field will store the salesforce Id of the impacted record.</inlineHelpText>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/Log_Trace_Utils__mdt/Log_Trace_Utils__mdt.object-meta.xml
<CustomObject>
    <label>Log Trace Util</label>
    <pluralLabel>Log Trace Util</pluralLabel>
</CustomObject>

force-app/main/objects/Log_Trace_Utils__mdt/fields/Is_Extension_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Extension_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is true, then the Override class will be used to process the Platform Event data and store it into a Salesforce object</description>
    <inlineHelpText>If this checkbox is true, then the Override class will be used to process the Platform Event data and store it into a Salesforce object</inlineHelpText>
    <label>Is Extension Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Trace_Utils__mdt/fields/Logging_Extension_Class__c.field-meta.xml
<CustomField>
    <fullName>Logging_Extension_Class__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for Platform Event</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for  Platform Event</inlineHelpText>
    <label>Logging Extension Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/classes/FlowExecutionEventHandler.cls
/**********************************************************************************************
* @Author:      Ranjan Singh
* @Date:        26th July 2023
* @Description: Handler class for FlowExecutionErrorEventFlow Flow.
*               The FlowExecutionEventHandler class is invoked from FlowExecutionErrorEventFlow to log flow related error info to Error Log object.
*               It provides a mechanism to process and log the error events based on custom metadata settings.
* @TestClass:   TBD 
***********************************************************************************************/
public with sharing class FlowExecutionEventHandler {
    /**
     * @Title: TRIGGER_METADATA
     * @Description:Constant variable to hold the name of the Custom Metadata Type record used for configuration.
    **/
    public static final string TRIGGER_METADATA = 'Flow_Error_Logging_Utils';
    /**
     * @Title: afterInsert
     * @Description:Invocable method that handles the insertion of error logs based on FlowExecutionErrorEvent platform events.
	 *              It processes the events and logs them based on custom metadata settings.
	 * @param flowErrorEventList A list of FlowExecutionErrorEvent records containing error information from Flow executions.
    **/
    @InvocableMethod(label='Insert Error Log' description='Error Log will stire data from FlowExecutionErrorEvent' category= 'FlowExecutionErrorEvent')
    public static void insertFlowErrorEventLog(list<FlowExecutionErrorEvent> flowErrorEventList)
    {
        try
        {
            Log_Trace_Utils__mdt errorLogEventInstance = Log_Trace_Utils__mdt.getInstance(TRIGGER_METADATA);
            if(errorLogEventInstance?.Is_Extension_Required__c && String.isNotBlank(errorLogEventInstance?.Logging_Extension_Class__c))
            {
                //Dynamically fetch the extension handler class and invoke the method. You can create a new class extending LoggerInterface and write your logging logic there.
                callExtensionClass(errorLogEventInstance, flowErrorEventList);                     
            }else
            {
                list<ErrorLog__c> errorLogList = new list<ErrorLog__c>(); // you can change this to your organization's error logging object here or at the custom metadat level
                for(FlowExecutionErrorEvent flowErrorInstance : flowErrorEventList)
                {
                    //instantiate the error logging object and feed the error information from PE 
                    errorLogList.add(new ErrorLog__c(
                        Record_Id__c = flowErrorInstance.RelatedRecordId, 
                        Error_Message__c = flowErrorInstance.ErrorMessage,
                        Component_Name__c = flowErrorInstance.FlowApiName,
                        Current_User__c = flowErrorInstance.UserId,
                        Error_Source__c = 'Flow',
                        Exception_Type__c = flowErrorInstance.EventType,
                        Flow_Element_Type__c = flowErrorInstance.ElementType,
                        Flow_Element_API_Name__c = flowErrorInstance.ElementApiName,
                        Flow_Context_Record_Id__c = flowErrorInstance.ContextRecordId,
                        Flow_Context_Object__c = flowErrorInstance.ContextObject
                    ));  
                }
                list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);
            }
        }catch(Exception ee)
        {
            
        }
    }
    @TestVisible
    private static void callExtensionClass(Log_Trace_Utils__mdt errorLogEventInstance, list<FlowExecutionErrorEvent> flowErrorEventList)
    {
        //Dynamically fetch the extension handler class and invoke the method. You can create a new class extending LoggerInterface and write your logging logic there.
        Type classType = Type.forName(errorLogEventInstance.Logging_Extension_Class__c);  
        LoggerInterface errorLogInterface = (LoggerInterface)classType.newInstance();
        errorLogInterface.execute(flowErrorEventList);    
    }
}