force-app/main/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/ErrorLog__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This field will store the impacted component(Apex class,lightning component,Workflow,Process builder,Flow)&apos;s name</description>
    <label>Component Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the error message of the actual exception</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <inlineHelpText>This field will store the source of error from where the error has invoked.</inlineHelpText>
    <label>Error Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</description>
    <inlineHelpText>This field will store the details of exception type, such as DmlException, ListException, SObjectException, and so on</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>START</fullName>
            </value>
            <value>
                <fullName>EXECUTE</fullName>
            </value>
            <value>
                <fullName>FINISH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/objects/ErrorLog__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <inlineHelpText>This field will store the salesforce Id of the impacted record.</inlineHelpText>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>This field will store the stack trace of exception. If exception is originated from APEX DML</description>
    <inlineHelpText>This field will store the stack trace of exception. If exception is originated from APEX DML</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/classes/InterfaceBatchErrorLogExtension.cls
/**********************************************************************************************
* @Author:      Ranjan Singh
* @Date:        24th July 2023
* @Description: The InterfaceBatchErrorLogExtension class provides a utility method to process a list of BatchApexErrorEvent records
*               and create corresponding ErrorLog__c records to log batch apex errors and exceptions.
*               logging the error information by invoking an external logging extension using LoggerInterface
* @TestClass:   BatchApexErrorEventTest 
***********************************************************************************************/
public with sharing class InterfaceBatchErrorLogExtension implements LoggerInterface{
    /**
     * @Title: execute
     * @Description:Processes a list of BatchApexErrorEvent records and creates ErrorLog__c records to log batch apex errors and exceptions.
	 * @param batchErrorEventList The list of BatchApexErrorEvent records to process.
    **/
    public static void execute(list<BatchApexErrorEvent> batchErrorEventList)
    {
        set<Id> asyncApexJobIds = new set<Id>();
        list<ErrorLog__c> errorLogList = new list<ErrorLog__c>(); 
        for(BatchApexErrorEvent batchInst : batchErrorEventList)
        {
            asyncApexJobIds.add(batchInst.AsyncApexJobId);
        }
        Map<Id,AsyncApexJob> asyncIdJobMap = new Map<Id,AsyncApexJob>([SELECT Id, ApexClass.Name 
                                                                       FROM AsyncApexJob 
                                                                       WHERE Id IN :asyncApexJobIds]
                                                                     );        
        
        for(BatchApexErrorEvent errorLogInstance : batchErrorEventList)
        {
            errorLogList.add(new ErrorLog__c(
                Component_Name__c = asyncIdJobMap.get(errorLogInstance.AsyncApexJobId)?.ApexClass.Name ,
                Error_Message__c = errorLogInstance.Message,
                Error_Source__c = 'Batch Apex',
                Exception_Type__c = errorLogInstance.ExceptionType,
                Stack_Trace__c = errorLogInstance.StackTrace,
                Phase__c = errorLogInstance.Phase,
                Record_Id__c = errorLogInstance.JobScope
            ));
        }
        list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);
    }
}